### ISSUE TITLE
issue running `rosservice call /generate_world`

### ISSUE THREAD

**Issue by eliasfrimanns** [EEEManchester/gazebosim_world_generator#1]
I wanted to try generating custom_env2, but I'm stuck getting this error message. Do you know how I can fix it? I have sourced to both to `setup.bash` in `devel` and sourced to `/opt/ros/melodic/setup.bash` since I am using melodic (running Ubuntu 18.04). 
```
rosservice call /generate_world "map_file: 'src/gazebosim_world_generator/maps/custom_env2.tiff'  config_file: 'src/gazebosim_world_generator/config/custom_env2.yaml' "
Traceback (most recent call last):
  File "/opt/ros/melodic/bin/rosservice", line 35, in <module>
    rosservice.rosservicemain()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosservice/__init__.py", line 749, in rosservicemain
    _rosservice_cmd_call(argv)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosservice/__init__.py", line 610, in _rosservice_cmd_call
    service_args.append(yaml.safe_load(arg))
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<string>", line 1, column 1:
    map_file: 'src/gazebosim_world_g ... 
    ^
expected <block end>, but found '<scalar>'
  in "<string>", line 1, column 66:
     ... nerator/maps/custom_env2.tiff'  config_file: 'src/gazebosim_worl ... 
                                         ^
```

**Comment by eliasfrimanns** [comment]
I found out that the command has to be changed to
```
rosservice call /generate_world '{map_file: "src/gazebosim_world_generator/maps/custom_env2.tiff", config_file: "src/gazebosim_world_generator/config/custom_env2.yaml"}'
```
in order for it to be compatible with yaml.
